//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public int book_id { get; set; }
        public string book_name { get; set; }
        public string author_name { get; set; }
        public Nullable<float> price { get; set; }
        public string summary { get; set; }
        public Nullable<System.DateTime> publish_date { get; set; }
    }
}
